### ISSUE TITLE
Unable to access *opcache_gui.php in magento2 setup

### ISSUE THREAD

**Issue by zorik01** [magenx/Magento-nginx-config#15] opened 2016-08-28 17:10 UTC
Unable to access "Opcache interface  http://www.${MAGE_DOMAIN}/${OPCACHE_FILE}_opcache_gui.php" in magento2 setup.

possible fix, file: magento2/sites-available/magento2.conf
, line:81
change: location ~ (index|get|static|report|404|503)\.php$ {
to location ~ (index|get|static|report|opcache_gui|404|503)\.php$ {

or we can modify it to allow white listed IPs only

**Comment by magenx** [comment] 2016-08-28 19:10
yes,
but this is not a bug.
it will be fixed "better" way in the next release soon.

**Closed** 2016-09-27 17:17 UTC
